SELECT
    COUNTRIES.COUNTRY_NAME AS 'País',
    IF(REGIONS.REGION_NAME = 'Europe', 'incluído', 'não incluído') AS 'Status Inclusão'
FROM hr.countries AS COUNTRIES
INNER JOIN hr.regions AS REGIONS ON REGIONS.REGION_ID = COUNTRIES.REGION_ID
ORDER BY COUNTRIES.COUNTRY_NAME;
