USE hr;

DELIMITER $$

CREATE PROCEDURE exibir_historico_completo_por_funcionario(IN email VARCHAR(50))
BEGIN
SELECT
CONCAT(T1.FIRST_NAME, ' ', LAST_NAME) AS 'Nome completo',
T2.DEPARTMENT_NAME AS 'Departamento',
T4.JOB_TITLE AS 'Cargo'
FROM hr.employees AS T1
INNER JOIN hr.job_history AS T3
ON T1.EMPLOYEE_ID = T3.EMPLOYEE_ID
INNER JOIN hr.departments AS T2
ON T3.DEPARTMENT_ID = T2.DEPARTMENT_ID
INNER JOIN hr.jobs AS T4
ON T3.JOB_ID = T4.JOB_ID
WHERE T1.EMAIL = email
ORDER BY T2.DEPARTMENT_NAME ASC, T4.JOB_TITLE ASC;
END $$

DELIMITER ;
