SELECT
    UCASE(CONCAT(EMPLOY.FIRST_NAME, ' ', EMPLOY.LAST_NAME)) AS 'Nome completo',
    HISTORY.START_DATE AS 'Data de início',
    EMPLOY.SALARY AS 'Salário'
FROM
    hr.employees AS EMPLOY
        INNER JOIN
    hr.job_history AS HISTORY ON HISTORY.EMPLOYEE_ID = EMPLOY.EMPLOYEE_ID
WHERE MONTH(HISTORY.START_DATE) IN (01, 02, 03)
ORDER BY CONCAT(FIRST_NAME, ' ', LAST_NAME), HISTORY.START_DATE;
