SELECT
UCASE(CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME)) AS 'Nome completo',
JS.START_DATE AS 'Data de início',
E.SALARY AS 'Salário'
FROM hr.employees E INNER JOIN hr.job_history JS
ON E.EMPLOYEE_ID = JS.EMPLOYEE_ID
WHERE SUBSTRING(JS.START_DATE, 6, 2) IN (01, 02, 03)
ORDER BY CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME), JS.START_DATE;
