SELECT 
    J.JOB_TITLE AS `Cargo`,
    ROUND(MAX_SALARY / 12, 2) AS `Média máxima mensal`,
    ROUND(MIN_SALARY / 12, 2) AS `Média mínima mensal`,
    CASE
        WHEN MAX_SALARY BETWEEN 5000 AND 10000 THEN MAX_SALARY - MIN_SALARY
        WHEN MAX_SALARY BETWEEN 10001 AND 20000 THEN MAX_SALARY - MIN_SALARY
        WHEN MAX_SALARY BETWEEN 20001 AND 30000 THEN MAX_SALARY - MIN_SALARY
        WHEN MAX_SALARY > 30001 THEN MAX_SALARY - MIN_SALARY
        ELSE MAX_SALARY
    END AS `Variação Salarial`
FROM
    hr.jobs AS J
ORDER BY `Variação Salarial` ASC , `Cargo` ASC;
