SELECT JOB_ID AS 'Cargo', AVG(SALARY), 
CASE
WHEN AVG(SALARY) < 5801 THEN 'Júnior'
WHEN AVG(SALARY) BETWEEN 5801 AND 7500 THEN 'Pleno'
WHEN AVG(SALARY) BETWEEN 7501 AND 10500 THEN 'Sênior'
WHEN AVG(SALARY) > 10500 THEN 'CEO'
END AS 'Senioridade'
FROM hr.employees
GROUP BY JOB_ID ORDER BY AVG(SALARY), JOB_ID;
