SELECT
CONCAT(FIRST_NAME, ' ' ,LAST_NAME) AS 'Nome completo',
DATE_FORMAT(START_DATE, "%d/%m/%Y") AS 'Data de início',
DATE_FORMAT(END_DATE, "%d/%m/%Y") AS 'Data de rescisão',
ROUND(DATEDIFF(END_DATE, START_DATE) / 365, 2) AS 'Anos trabalhados'
FROM hr.employees E INNER JOIN hr.job_history JS
ON E.EMPLOYEE_ID = JS.EMPLOYEE_ID
ORDER BY CONCAT(FIRST_NAME, ' ' ,LAST_NAME), ROUND(DATEDIFF(END_DATE, START_DATE) / 365, 2);
