USE hr;
DELIMITER $$

CREATE FUNCTION buscar_quantidade_de_empregos_por_funcionario(email VARCHAR(100))
RETURNS INT READS SQL DATA
BEGIN
DECLARE CargoNumber INT;
SELECT
COUNT(H.EMPLOYEE_ID)
FROM job_history AS H
INNER JOIN employees AS E
ON H.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE E.EMAIL = email INTO CargoNumber;
RETURN CargoNumber;
END $$

DELIMITER ;
