DELIMITER $$
CREATE FUNCTION  buscar_quantidade_de_empregos_por_funcionario(e VARCHAR(100))
RETURNS INT READS SQL DATA
BEGIN
DECLARE VALOR INT;
SELECT count(*) FROM hr.employees AS E
INNER JOIN hr.job_history AS H
ON E.EMPLOYEE_ID = H.EMPLOYEE_ID
WHERE EMAIL = e INTO VALOR;
RETURN VALOR;
END $$
DELIMITER ;
